newzoo/config/routes.rb
Newzoo::Application.routes.draw do
  devise_for :users

  resources :students
  resources :operates
  root :to => redirect('/students')
  match "set" => "students#set"
  match "memo" => "operates#memo"
  match "spin" => "students#spin"
  match "beach" => "students#beach"
  match "food" => "students#food"
end

newzoo/app/models/operate.rb
class Operate < ActiveRecord::Base
 attr_accessible :Hmd, :Homework, :HomeworkDescription, :Homework2
end

newzoo/app/models/student.rb
class Student < ActiveRecord::Base
 attr_accessible :a, :b, :c,:d, :e, :f, :g, :h, :i
end

newzoo/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

newzoo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

newzoo/app/controllers/operates_controller.rb
class OperatesController < ApplicationController
  before_filter:authenticate_user!
   def index#ok
     @operates = Operate.all
   end
   #def set
   #  @operates = Operate.all
   #end
  def update #ok
     @operate = Operate.find params[:id]
     @operate.update_attributes!(params[:operate])
     respond_to do |client_wants|
     client_wants.html {  redirect_to operate_path(@operate)  } # as before
     client_wants.xml  {  render :xml => @operate.to_xml    }
     end
   end
   def memo #0k
    @operates = Operate.all
   end
   def new #ok

   end
   def destroy #ok
     @operate= Operate.find(params[:id])
     @operate.destroy
     flash[:notice] = "Operate '#{@operate.id}' deleted."
     redirect_to operates_path
   end

   def edit #ok
     @operate = Operate.find params[:id]
   end


   def create #ok
     @operate = Operate.create!(params[:operate])
     redirect_to operates_path
   end
   def show #ok
     id = params[:id] # retrieve HOmework ID from URI route
     @operate = Operate.find(id) # look up studnet by unique ID
     #@student = Student.all
     # will render app/views/operates/show.html.haml by default
   end
end

newzoo/app/controllers/students_controller.rb
#This file is app/controllers/movies_controller.rb
 class StudentsController < ApplicationController
   before_filter:authenticate_user!
   def index

     @students = Student.all
   end
   def set
     @students = Student.all
   end
   def test

   end
   def spin
   end
   def beach
   end
   def food
   end
   def update
     @student = Student.find params[:id]
     @student.update_attributes!(params[:student])
     respond_to do |client_wants|
     client_wants.html {  redirect_to student_path(@student)  } # as before
     client_wants.xml  {  render :xml => @student.to_xml    }
     end
   end
   def new

   end
   def destroy
     @student= Student.find(params[:id])
     @student.destroy
     flash[:notice] = "Student '#{@student.id}' deleted."
     redirect_to students_path
   end

   def edit
     @student = Student.find params[:id]
   end

#   def update
#     @student = Student.find params[:id]
#     @student.update_attributes!(params[:student])
#     flash[:notice] = "#{@student.title} was successfully updated."
#     redirect_to student_path(@student)
#   end
   def create
     @student = Student.create!(params[:student])
     redirect_to students_path
   end
   def show
     id = params[:id] # retrieve movie ID from URI route
     @student = Student.find(id) # look up movie by unique ID
     # will render app/views/movies/show.html.haml by default
   end
 end

newzoo/app/helpers/application_helper.rb
module ApplicationHelper
end

newzoo/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title ZOO!!!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = yield

%p.notice= notice
%p.alert= alert
- if current_user
  = link_to('logout', destroy_user_session_path, :method => :delete)
  |
  \#{link_to('change password', edit_registration_path(:user))}
- else
  = link_to('Register', new_registration_path(:user))
  |
  \#{link_to('login', new_session_path(:user))}
  -# = link_to 'beach', :controller => :operates, :action => :index

newzoo/app/views/operates/_operate_form.html.haml
= label :operate, :Hmd, 'Homework ID'
= text_field :operate, :Hmd

= label :operate, :Homework, 'Date Of Memo Begins'
= date_select :operate, :Homework

= label :operate, :HomeworkDescription, 'Description of Memo'
= text_area :operate, :HomeworkDescription

= label :operate, :Homework2, 'Date Of Memo Ends'
= date_select :operate, :Homework2

newzoo/app/views/operates/edit.html.haml
%h2 Edit The Existing Students Homeworks/Assignments

= form_tag operate_path(@operate), :method => :put do
  = render :partial => 'operate_form'
  = submit_tag 'Update Students Home Works!'
= link_to 'Back to Student Homework', operates_path

newzoo/app/views/operates/index.html.haml
%h2 All The Information About Student Home Works
        
%table#operates
  %thead
    %tr      
      %th Home Work ID      
      %th Home Work begins->
      %th Home Work Description->
      %th Home Work ends->
  %tbody
    - @operates.each do |operate|
      %tr        
        %td= operate.Hmd
        %td= operate.Homework
        %td= operate.HomeworkDescription
        %td= operate.Homework2
        %td= link_to "More about #{operate.Hmd}", operate_path(operate)
= link_to 'Add New HomeWork Memo', new_operate_path 

newzoo/app/views/operates/memo.html.haml
%h2 All The Information About Student Home Works
        
%table#operates
  %thead
    %tr         
      %th Home Work ID   
      %th Home Work begins->
      %th Home Work Description->
      %th Home Work ends->
  %tbody
    - @operates.each do |operate|
      %tr        
        %td= operate.Hmd
        %td= operate.Homework
        %td= operate.HomeworkDescription
        %td= operate.Homework2
        %td= link_to "More about #{operate.Hmd}", operate_path(operate)
= link_to 'Add New HomeWork Memo', new_operate_path 
= link_to 'Back to Home Page', students_path

newzoo/app/views/operates/new.html.haml
%h2 Create New Assignment/Memo For Students

= form_tag operates_path, :method => :post do
    
  = label :operate, :Hmd, 'Homework ID'
  = text_field :operate, :Hmd

  = label :operate, :Homework, 'Date Of Memo Begins'
  = date_select :operate, :Homework

  = label :operate, :HomeworkDescription, 'Description of Memo'
  = text_area :operate, :HomeworkDescription

  = label :operate, :Homework2, 'Date Of Memo Ends'
  = date_select :operate, :Homework2


  = submit_tag 'Save Home Work!'
= link_to 'Back to Home Page', students_path

newzoo/app/views/operates/show.html.haml
%h2 Details about #{@operate.id}
 
%ul#details
  %li
    Homework ID:
    = @operate.Hmd
  %li
    Start Homework:
    = @operate.Homework
  %li
    Homework Description:
    = @operate.HomeworkDescription
  %li
    End Homework:
    = @operate.Homework2

= link_to 'Edit info**'    , edit_operate_path(@operate)
= link_to 'Delete**'       , operate_path(@operate), :method => :delete
= link_to 'Move to Home work page**'     , operates_path
= link_to 'Back to Homepage', students_path

newzoo/app/views/students/_student_form.html.haml
= label :student, :a, 'Name'
= text_field :student, :a

= label :student, :b, 'Grade'
= text_field :student, :b
        
= label :student, :c, 'class'
= text_field :student, :c  
           
= label :student, :d, 'Seatnumber'
= text_field :student, :d


                
= label :student, :e, 'Grouping'
= text_field :student, :e

= label :student, :f, 'Job'
= text_field :student, :f

= label :student, :g, 'Pet Number'
= text_field :student, :g

= label :student, :h, 'Pet type'
= text_field :student, :h

= label :student, :i, 'Food'
= text_field :student, :i

newzoo/app/views/students/beach.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <style>
      body {
        margin: 0px;
        padding: 0px;
      }
      canvas {
        border: 1px solid #9C9898;
      }
        
    </style>
    <script src="http://www.html5canvastutorials.com/libraries/kinetic-v4.0.1.js"></script>
    <script>
      function loadImages(sources, callback) {
        var assetDir = "/assets/";
        var images = {};
        var loadedImages = 0;
        var numImages = 0;
        

        for(var src in sources) {
          numImages++;
        }
        for(var src in sources) {
          images[src] = new Image();
          images[src].onload = function() {
            if(++loadedImages >= numImages) {
              callback(images);
            }
          };
          images[src].src = assetDir + sources[src];
        }
      }
      function isNearOutline(animal, outline) {
        var a = animal;
        var o = outline;
        if(a.attrs.x > o.x - 20 && a.attrs.x < o.x + 20 && a.attrs.y > o.y - 20 && a.attrs.y < o.y + 20) {
          return true;
        }
        else {
          return false;
        }
      }
      function drawBackground(background, beachImg, text) {
        var canvas = background.getCanvas();
        var context = background.getContext();

        context.drawImage(beachImg, 0, 0);
        context.font = "20pt Calibri";
        context.textAlign = "center";
        context.fillStyle = "black";
        context.fillText(text, background.getStage().getWidth() / 2, 40);
      }
      function initStage(images) {
        var stage = new Kinetic.Stage({
          container: "container",
          width: 803,
          height: 599
        });
        var background = new Kinetic.Layer();
        var animalLayer = new Kinetic.Layer();
        var animalShapes = [];
        var score = 0;

        // image positions
        var animals = {
          snake: {
            x: 10,
            y: 70
          },
          giraffe: {
            x: 90,
            y: 1
          },
          monkey: {
            x: 275,
            y: 70
          },
          lion: {
            x: 500,
            y: 70
          },
        };

        var outlines = {
          snake_black: {
            x: 275,
            y: 350
          },
          giraffe_black: {
            x: 390,
            y: 250
          },
          monkey_black: {
            x: 300,
            y: 420
          },
          lion_black: {
            x: 100,
            y: 390
          },
        };

        // create draggable animals
        for(var key in animals) {
          // anonymous function to induce scope
          (function() {
            var privKey = key;
            var anim = animals[key];

            var animal = new Kinetic.Image({
              image: images[key],
              x: anim.x,
              y: anim.y,
              draggable: true
            });
            
            animal.createImageBuffer();

            animal.on("dragstart", function() {
              animal.moveToTop();
              animalLayer.draw();
            });
            /*
             * check if animal is in the right spot and
             * snap into place if it is
             */
            animal.on("dragend", function() {
              var outline = outlines[privKey + "_black"];
              if(!animal.inRightPlace && isNearOutline(animal, outline)) {
                animal.attrs.x = outline.x;
                animal.attrs.y = outline.y;
                animalLayer.draw();
                // disable drag and drop
                animal.setDraggable(false);
                animal.inRightPlace = true;

                if(++score >= 4) {
                  var text = "YEAH!!!!!!"
                  drawBackground(background, images.beach, text);
                }
              }
            });
            // make animal glow on mouseover
            animal.on("mouseover", function() {
              animal.setImage(images[privKey + "_glow"]);
              animalLayer.draw();
              document.body.style.cursor = "pointer";
            });
            // return animal on mouseout
            animal.on("mouseout", function() {
              animal.setImage(images[privKey]);
              animalLayer.draw();
              document.body.style.cursor = "default";
            });

            animal.on("dragmove", function() {
              document.body.style.cursor = "pointer";
            });

            animalLayer.add(animal);
            animalShapes.push(animal);
          })();
        }

        // create animal outlines
        for(var key in outlines) {
          // anonymous function to induce scope
          (function() {
            var imageObj = images[key];
            var out = outlines[key];

            var outline = new Kinetic.Image({
              image: imageObj,
              x: out.x,
              y: out.y
            });

            animalLayer.add(outline);
          })();
        }

        stage.add(background);
        stage.add(animalLayer);

        drawBackground(background, images.beach, "put the animals to where it belongs!");
      }
      
      window.onload = function() {
        
        var sources = {
          beach: "goo.jpg",
          snake: "snake.png",
          snake_glow: "snake-glow.png",
          snake_black: "snake-black.png",
          lion: "lion.png",
          lion_glow: "lion-glow.png",
          lion_black: "lion-black.png",
          monkey: "monkey.png",
          monkey_glow: "monkey-glow.png",
          monkey_black: "monkey-black.png",
          giraffe: "giraffe.png",
          giraffe_glow: "giraffe-glow.png",
          giraffe_black: "giraffe-black.png",
        };
        loadImages(sources, initStage);
      };

    </script>
  </head>
  <body background="/assets/zoo.png">
    <div id="container"></div>
    <IMG STYLE="position:absolute; TOP:650PX; LEFT:5PX; WIDTH:150PX; HEIGHT:150PX" SRC="/assets/1.gif">

  </body>
  <a href="/students">Back to Home Page</a>
</html>

newzoo/app/views/students/edit.html.haml
%h2 Edit Existing Student

= form_tag student_path(@student), :method => :put do
  = render :partial => 'student_form'
  = submit_tag 'Update Student Info'

newzoo/app/views/students/food.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <style>
      body {
        margin: 0px;
        padding: 0px;
      }
      canvas {
        border: 1px solid #9C9898;
      }
        
    </style>
    <script src="http://www.html5canvastutorials.com/libraries/kinetic-v4.0.1.js"></script>
    <script>
      function loadImages(sources, callback) {
        var assetDir = "/assets/";
        var images = {};
        var loadedImages = 0;
        var numImages = 0;
        

        for(var src in sources) {
          numImages++;
        }
        for(var src in sources) {
          images[src] = new Image();
          images[src].onload = function() {
            if(++loadedImages >= numImages) {
              callback(images);
            }
          };
          images[src].src = assetDir + sources[src];
        }
      }
      function isNearOutline(animal, outline) {
        var a = animal;
        var o = outline;
        if(a.attrs.x > o.x - 20 && a.attrs.x < o.x + 20 && a.attrs.y > o.y - 20 && a.attrs.y < o.y + 20) {
          return true;
        }
        else {
          return false;
        }
      }
      function drawBackground(background, beachImg, text) {
        var canvas = background.getCanvas();
        var context = background.getContext();

        context.drawImage(beachImg, 0, 0);
        context.font = "20pt Calibri";
        context.textAlign = "center";
        context.fillStyle = "black";
        context.fillText(text, background.getStage().getWidth() / 2, 40);
      }
      function initStage(images) {
        var stage = new Kinetic.Stage({
          container: "container",
          width: 803,
          height: 599
        });
        var background = new Kinetic.Layer();
        var animalLayer = new Kinetic.Layer();
        var animalShapes = [];
        var score = 0;

        // image positions
        var animals = {
          snake: {
            x: 250,
            y: 70
          },
          lion: {
            x: 370,
            y: 270
          },
        };

        var outlines = {
          snake_black: {
            x: 380,
            y: 180
          },
          lion_black: {
            x: 30,
            y: 500
          },
        };

        // create draggable animals
        for(var key in animals) {
          // anonymous function to induce scope
          (function() {
            var privKey = key;
            var anim = animals[key];

            var animal = new Kinetic.Image({
              image: images[key],
              x: anim.x,
              y: anim.y,
              draggable: true
            });
            
            animal.createImageBuffer();

            animal.on("dragstart", function() {
              animal.moveToTop();
              animalLayer.draw();
            });
            /*
             * check if animal is in the right spot and
             * snap into place if it is
             */
            animal.on("dragend", function() {
              var outline = outlines[privKey + "_black"];
              if(!animal.inRightPlace && isNearOutline(animal, outline)) {
                animal.attrs.x = outline.x;
                animal.attrs.y = outline.y;
                animalLayer.draw();
                // disable drag and drop
                animal.setDraggable(false);
                animal.inRightPlace = true;

                if(++score >= 2) {
                  var text = "YEAH!!!!!!"
                  drawBackground(background, images.beach, text);
                }
              }
            });
            // make animal glow on mouseover
            animal.on("mouseover", function() {
              animal.setImage(images[privKey + "_glow"]);
              animalLayer.draw();
              document.body.style.cursor = "pointer";
            });
            // return animal on mouseout
            animal.on("mouseout", function() {
              animal.setImage(images[privKey]);
              animalLayer.draw();
              document.body.style.cursor = "default";
            });

            animal.on("dragmove", function() {
              document.body.style.cursor = "pointer";
            });

            animalLayer.add(animal);
            animalShapes.push(animal);
          })();
        }

        // create animal outlines
        for(var key in outlines) {
          // anonymous function to induce scope
          (function() {
            var imageObj = images[key];
            var out = outlines[key];

            var outline = new Kinetic.Image({
              image: imageObj,
              x: out.x,
              y: out.y
            });

            animalLayer.add(outline);
          })();
        }

        stage.add(background);
        stage.add(animalLayer);

        drawBackground(background, images.beach, "Please feed and clean our cute elephant!");
      }
      
      window.onload = function() {
        
        var sources = {
          beach: "goo.jpg",
          snake: "banana-02.png",
          snake_glow: "banana-02-01.png",
          snake_black: "good-01-01.png",
          lion: "shit-01.png",
          lion_glow: "shit-02-01.png",
          lion_black: "shitonbin-01.png",
        };
        loadImages(sources, initStage);
      };

    </script>
  </head>
    <IMG STYLE="position:absolute; TOP:650PX; LEFT:5PX; WIDTH:150PX; HEIGHT:150PX" SRC="/assets/1.gif">
    <div id="container"></div>
  </body>
  <a href="/students">Back to Home Page</a>
</html>

newzoo/app/views/students/index.html.haml
-#This file is app/views/movies/index.html.haml
%h2 Welcome to DaDu Elementary School in Hsinchu County 
-#%link(rel="stylesheet" type="text/css" href="style.css")

-#.page-heading
-#tabs
  %ul
    %li
      %a{:href => "#devices-tab"}Zoo1
    %li
      %a{:href => "#options-tab"}Zoo2
    %li
      %a{:href => "#reports-tab"}Zoo3
    %li
      %a{:href => "#notes-tab"}Zoo4


-#:javascript
  $(document).ready(function() {
  $( "#tabs" ).tabs();
  });
-#%P{:ALIGN => "center"}
-#%IMG{:ALT => "Image Map", :BORDER => "0", :HEIGHT => "25", :SRC => "/assets/map1.gif", :USEMAP => "#menuline", :WIDTH => "400"}/
-#%BODY
  %MAP{:NAME => "menuline"}
    %AREA{:COORDS => "0,0,100,24", :HREF => "index.htm", :SHAPE => "rect"}
    %AREA{:COORDS => "101,0,200,24", :HREF => "intro.htm", :SHAPE => "rect"}
    %AREA{:COORDS => "201,0,300,24", :HREF => "lesson21.htm", :SHAPE => "rect"}
    %AREA{:COORDS => "301,0,400,24", :HREF => "topics.htm", :SHAPE => "rect"}
-#test
  %h1 Hello
  %ul
    %li
      %a{:href => "#"} Thing One
    %li
      %a{:href => "#"} Thing Two
    %li
      %a{:href => "#"} Thing Three
    %li
      %a{:href => "#"} Thing Four
  .clear
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
-#devices-tab
  zoo1
-#<img src="/assets/zoo.png">
-# if current_user
  = link_to('logout', destroy_user_session_path, :method => :delete)
  | 
  = link_to('change password', edit_registration_path(:user))
    
%P{:ALIGN => "center"}
  %IMG{:ALT => "Image Map", :BORDER => "0", :HEIGHT => "599", :SRC => "/assets/zoo.png", :USEMAP => "#zooline", :WIDTH => "803"}/

  %BODY
    %MAP{:NAME => "zooline"}
      %AREA{:COORDS => "688,218,792,329", :SHAPE => "rect", :href => "set"}
      %AREA{:COORDS => "691,114,778,206", :SHAPE => "rect", :href => "memo"}
      %AREA{:COORDS => "662,440,786,578", :HREF => "food", :SHAPE => "rect"}
      %AREA{:COORDS => "163,152,616,444", :HREF => "beach", :SHAPE => "rect"}



%IMG{:SRC => "/assets/1.gif", :STYLE => "position:absolute; TOP:680PX; LEFT:5PX; WIDTH:150PX; HEIGHT:150PX"}/
      
-#%AREA{:COORDS => "301,0,400,24", :HREF => "topics.htm", :SHAPE => "rect"}
-#%div{:style => "margin-left: 250px; margin-top: -0px; height: 150px; background-color: transparent; width: 750px;"}/
-##id-top-bar{:calss => "top-bar", :style => "float: left; margin-top:-23px; height: 23px; width: 750px; background-color: transparent;"}/

-# else
  = link_to('Register', new_registration_path(:user))
  |
  = link_to('login', new_session_path(:user))

newzoo/app/views/students/new.html.haml
%h2 Create New Student

= form_tag students_path, :method => :post do

  = label :student, :a, 'Name'
  = text_field :student, :a

  = label :student, :b, 'Grade'
  = select :student, :b, ['1','2','3','4','5','6']
  
  = label :student, :c, 'Class'
  = select :student, :c, ['1','2','3','4','5']  
  
  = label :student, :d, 'Seatnumber'
  = select :student, :d, ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25']
  
  = label :student, :e, 'Grouping'
  = select :student, :e, ['A','B','C','D','E','F']

  = label :student, :f, 'Job'
  = select :student, :f, ['Feeding','Sweeping','Washing']

  -#= label :student, :g, 'Pet Number'
  -#= text_field :student, :g

  = label :student, :h, 'Pet type'
  = select :student, :h, ['Dog','Cat','Rabbit','Turtle','lion','Panda']

  = label :student, :i, 'Food'
  = select :student, :i, ['Banana','Meat','Carrot','Bamboo']


  = submit_tag 'Save Changes'
  = link_to 'Back to Home Page', students_path

newzoo/app/views/students/set.html.haml
%table#students
  %thead
    %tr
      %th Name
      %th Grade
      %th Class
      %th Seatnmber
      %th Grouping
      %th Job
      %th Pet Type
      %th Food

    %tbody
      - @students.each do |student|
        %tr
          %td= student.a
          %td= student.b
          %td= student.c
          %td= student.d
          %td= student.e
          %td= student.f
          %td= student.h
          %td= student.i
          %td= link_to "More about #{student.a}", student_path(student)
= link_to 'Add new student', new_student_path
= link_to 'Back to Main Page', students_path

newzoo/app/views/students/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@student.id}

%ul#details
  %li
    Name:
    = @student.a
  %li
    Grade:
    = @student.b
  %li
    Class:
    = @student.c
  %li
    Seatnumber:
    = @student.d
  %li
    Grouping:
    = @student.e
  %li
    Job:
    = @student.f
  %li
    Pet Number:
    = @student.g
  %li
    Pet type:
    = @student.h
  %li
    Food:
    = @student.i

= link_to 'Edit info', edit_student_path(@student)
= link_to 'Back to student list', students_path
= link_to 'Delete', student_path(@student), :method => :delete

newzoo/app/views/students/spin.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <style>
      body {
        margin: 0px;
        padding: 0px;
      }
    </style>
  </head>
  <body>
    <div id="container"></div>
    <script src="http://d3lp1msu2r81bx.cloudfront.net/kjs/js/lib/v4.2.0/kinetic-v4.2.0.js"></script>
    <script>
      var stage = new Kinetic.Stage({
        container: 'container',
        width: 578,
        height: 200
      });
      var layer = new Kinetic.Layer();

      /*
       * leave center point positioned
       * at the default which is at the center
       * of the hexagon
       */
      var blueHex = new Kinetic.RegularPolygon({
        x: 100,
        y: stage.getHeight() / 2,
        sides: 6,
        radius: 70,
        fill: '#00D2FF',
        stroke: 'black',
        strokeWidth: 4,
        draggable: true
      });

      var yellowHex = new Kinetic.RegularPolygon({
        x: stage.getWidth() / 2,
        y: stage.getHeight() / 2,
        sides: 6,
        radius: 70,
        fill: 'yellow',
        stroke: 'black',
        strokeWidth: 4,
        draggable: true
      });

      /*
       * move center point to right side
       * of hexagon
       */
      var redHex = "/assets/map1.gif" 




      layer.add(blueHex);
      layer.add(yellowHex);
      layer.add(redHex);
      stage.add(layer);

      var period = 2000;

      var anim = new Kinetic.Animation(function(frame) {
        var scale = Math.sin(frame.time * 2 * Math.PI / period) + 0.001;
        // scale x and y
        blueHex.setScale(scale);
        // scale only y
        yellowHex.setScale(1, scale);
        // scale only x
        redHex.setScale(scale, 1);
      }, layer);

      anim.start();
    </script>
  </body>
</html>

newzoo/app/views/students/test.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <style>
      body {
        margin: 0px;
        padding: 0px;
      }
      canvas {
        border: 1px solid #9C9898;
      }
      #tango {
        position: absolute;
        top: 10px;
        left: 10px;
        padding: 10px;
      }
      #container {
        <!-- background-image: url("http://www.html5canvastutorials.com/demos/assets/blue-background.jpg"); -->
        display: inline-block;
        overflow: hidden;
        height: 365px;
        width: 580px;
      }
    </style>
  </head>
  <body onmousedown="return false;">
    <div id="container"></div>
    <input type="button" id="tango" value="Tango!">
    <script src="http://www.html5canvastutorials.com/libraries/kinetic-v4.3.0-beta2.js"></script>
    <script>
      function tango(layer) {
        for(var n = 0; n < layer.getChildren().length; n++) {
          var shape = layer.getChildren()[n];
          var stage = shape.getStage();
          shape.transitionTo({
            rotation: Math.random() * Math.PI * 2,
            radius: Math.random() * 100 + 20,
            x: Math.random() * stage.getWidth(),
            y: Math.random() * stage.getHeight(),
            opacity: Math.random(),
            duration: 1,
            easing: 'ease-in-out'
          });
        }
      }
      var stage = new Kinetic.Stage({
        container: 'container',
        width: 578,
        height: 363
      });

      var layer = new Kinetic.Layer();

      var colors = ['red', 'orange', 'yellow', 'green', 'blue', 'purple'];
      for(var n = 0; n < 10; n++) {
        var shape = new Kinetic.RegularPolygon({
          x: Math.random() * stage.getWidth(),
          y: Math.random() * stage.getHeight(),
          sides: Math.ceil(Math.random() * 5 + 3),
          radius: Math.random() * 100 + 20,
          fill: colors[Math.round(Math.random() * 5)],
          stroke: 'black',
          opacity: Math.random(),
          strokeWidth: 4,
          draggable: true
        });

        layer.add(shape);
      }

      stage.add(layer);

      document.getElementById('tango').addEventListener('click', function() {
        tango(layer);
      }, false);
    </script>
  </body>
</html>